### ISSUE TITLE
Combobox nested Anchor component triggers onSelectedItemChange

### ISSUE THREAD

**Issue by jsheppard-twilio** [twilio-labs/paste#2079] opened 2021-11-29 12:38 UTC
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
If we use the Anchor component within the optionTemplate, when a users clicks this Anchor it first triggers the onSelectedItemChange and then the anchor url redirect.

**To Reproduce**
https://codesandbox.io/s/composable-cells-datagrid-forked-0w2yh?file=/src/index.tsx
Sandbox shows the dropdown with external icon.
Click on an option, and you'll see the alert for the onSelectedItemChange then the url will open in a new tab. 

**Expected behavior**
I'd expect once a users clicks on the Anchor, the onSelectedItemChange wouldn't fire, and only the url change would take place.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by kylegilbreath** [comment] 2021-11-30 18:23
Thanks for reporting this @jsheppard-twilio! I was hoping you could provide some more context on what you are trying to do? I'm wondering if the Combobox is the correct control to use for the task. I'm not entirely sure what the desired interaction should be if you were using a Combobox item to link out to an external url.

Based on the description, we might suggest using a [Menu](https://paste.twilio.design/components/menu/) component in instead of a combobox.

**Comment by jsheppard-twilio** [comment] 2021-12-01 14:51
Design was following the example which shows the external link icon. 

Combobox using Option Template: https://paste.twilio.design/components/combobox/#combobox-using-option-template

We have a list of related accounts which varies in length between accounts. So users have the need to be able to filter the list, rather than a fixed Menu.

**Comment by loreina** [comment] 2021-12-06 15:04
Hi @jsheppard-twilio, in the example we're using `LinkExternalIcon` to show that an icon can be displayed in a combobox item. Technically, Anchor shouldn't be nested inside a combobox item as only text is permitted content in an [option element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option). Did you have a use case for using Anchor here?

**Comment by SiTaggart** [comment] 2021-12-15 02:42
Hi there,

Sorry for the delay, the holiday season is upon us, and we're a bit slow to respond.

OK, so the unfortunate reality is that this is working as expected. The reason being, for this to be an accessible user interaction,  I must be able to navigate to your page (which is now an option I can choose in your combobox) using just my keyboard. 

Keyboard navigation with comboboxes works with arrow keys. When focused inside the input, I can press up and down and navigate through the list of options, whilst still having my cursor placed in the input. Focus never moved. What that means is, I can't actually click the anchor. I can only cause an onChange event. The combobox has to respond to my selection, and then navigate based on that selection.

This is why we don't recommend placing focusable elements inside an `optionTemplate`. 

It is of course understandable that as a mouse user, I might want to right-click and open the option in a new tab, or hold command and click to open in a new tab. So placing an anchor element inside the `optionTemplate` is an acceptable use case, **but you must _also_** respond to the `onSelectedItemChange` and perform the same action via JavaScript.

I hope that makes sense. It's quite a complex user interaction to describe in written form. Ultimately, though, I will likely close this issue with a "works as intended" note.

**Closed** 2022-04-08 14:49 UTC
Labels: Type: Bug
