### ISSUE TITLE
Physical properties causing issues in RTL layouts

### ISSUE THREAD

**Issue by gialletty** [twilio-labs/paste#2267] opened 2022-03-04 12:55 UTC
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
The use of physical properties are causing a few issues when displaying RTL languages. I noticed this while browsing the Storybook.

**To Reproduce**
1. Go to [TableOfContents Story](https://paste-storybook.twilio.design/?path=/story/website-tableofcontents--default-table-of-contents)
2. Switch to RTL locale by clicking on globe icon in header bar
3. Notice styling issues

**Expected behavior**
Border position should be flipped as expected for RTL

**Additional context**
I know that some work around i18n is currently in progress and probably this report is redundant, but since I noticed that RTL are supported I wanted to point this out. It's possible that we might need to replace physical properties with logical ones in other components as well. A good read regarding this issue would be [RTL Styling 101](https://rtlstyling.com/posts/rtl-styling).

**Comment by shleewhite** [comment] 2022-03-04 17:36
Hi @gialletty! You are right, we are currently working on an internationalization epic. 

We are in the first phase right now, removing hardcoded strings from our components. We have also done a spike on using start/end CSS properties instead of left/right and added the storybook toggle to see how much we have to do 😂 

I am going to close this because it is not a bug and we have ticketed work to support RTL languages.

**Closed by shleewhite** 2022-03-04 17:36 UTC
Labels: Type: Bug
