### ISSUE TITLE
Tooltip on a disabled button doesn't show tooltip

### ISSUE THREAD

**Issue by moyara** [twilio-labs/paste#1081] opened 2021-01-08 23:42 UTC
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**
Tooltip with a disabled Button doesn't allow to show the tooltip over the button.

**To Reproduce**
```
<Tooltip
    text={"my tooltip"}
>
    <Button disabled={true}>
        my button
    </Button>
</Tooltip>
```

**Expected behavior**
Expected to show the tooltip even though the button is disabled. The UX expectation is to show the reason why the button is disabled as a tooltip. Not sure if it's expected but I think tooltip's status should be determined by itself not by child component inside.

**Comment by SiTaggart** [comment] 2021-01-09 00:47
Hi @moyara, thanks for your contribution. The behavior you are seeing with the component is expected though, I'm afraid. 

As you know a Tooltip should show to the user upon hovering an element, but also on focus of that element. A Tooltip describes the element that triggers the tooltip. This is the key part of the expected behavior. A tooltip is directly associated to a trigger, and shows upon user events that occur on that trigger.

When an interactive HTML element is disable it no longer responds to user events. It's not focusable, it's not clickable, I don't think responds to any pointer event. Because of that, there is no event to trigger showing the tooltip. The triggering element is effectively, not there. Removed from the DOM.

If you wish to inform a user why something is disabled in the page, you will need to find an alternative way to communicate that. We often recommend just having some written text visible near the element itself, an inline message. Or if it's important, an showing Alert or popping a Toast on page load could work too.

I am going to close this issue though, as it is expected behavior.

**Closed by SiTaggart** 2021-01-09 00:47 UTC
Labels: Type: Bug
