### ISSUE TITLE
Making website responsive

### ISSUE THREAD

**Issue by ChaitanyaKaranam** [twilio-labs/paste#121] opened 2019-10-05 07:02 UTC
Looks like the website is not responsive. I can pick this up if no one is working on this

**Comment by TheSisb** [comment] 2019-10-07 16:20
Hey @ChaitanyaKaranam, thanks for the offer!  We wanted to hold off on that part until more of the system is built so that we can build the website with our system.  Specifically our layout components (grid & flex).  

I'll leave this open and marked as blocked for now.

**Comment by TheSisb** [comment] 2019-10-07 16:22
Actually, for grooming purposes I will mark this as a dupe of https://github.com/twilio-labs/paste/issues/66

**Closed by TheSisb** 2019-10-07 16:22 UTC
Labels: Area: Design, Area: Doc Site, Status: Blocked
