### ISSUE TITLE
Show px values for tokens

### ISSUE THREAD

**Issue by pguptaDS** [twilio-labs/paste#412] opened 2020-04-29 21:22 UTC
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

## Is this related to an existing Paste Component? Please link it here:
https://paste.twilio.design/tokens/

## Describe the functionality you're looking for
It would be very helpful to show the token values in px on the page along with rem values. As a designer, I work with px in sketch so every time I want to use the token values, I first have to convert it and then use it which slows down my workflow. Showing both rem and px values would help me in my conversations with FE engineers as well because they work in rems and I often find myself spending time converting px->rem or rem->px during our conversations.

**Comment by Angelangg** [comment] 2020-05-05 22:40
+1 on this issue

**Comment by SiTaggart** [comment] 2020-05-07 00:29
As this is a dupe of https://github.com/twilio-labs/paste/issues/98 I'm going to close this and track the work there

**Closed by SiTaggart** 2020-05-07 00:29 UTC
Labels: Area: Doc Site, Area: Tokens, Backlog, Type: Documentation, Type: Enhancement, Type: Feature Request, good first issue
