### ISSUE TITLE
Combobox dropdown doesn't render in correct position

### ISSUE THREAD

**Issue by bthomasstill** [twilio-labs/paste#3128] opened 2023-03-28 17:23 UTC
### Description

When I render a list of comboboxes and then scroll around (especially with the combobox open), the dropdown doesn't render in the correct place. There is some unexpected behavior in how it renders the dropdown in this situation. I've included a code sandbox example but it is actually more pronounced in my actual code.

### Link to Reproduction

https://codesandbox.io/s/silly-volhard-ztqjx9?file=/src/index.tsx

### Steps to reproduce

1. Go to open dialog.
2. Click on a combobox to open the dropdown list.
3. Scroll down so the dropdown is still in view. Repeat a few times.
4. The dropdown position seems to get confused about where it should be positioned.

### Paste Core Version

18

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by SiTaggart** [comment] 2023-03-28 22:48
Hi @bthomasstill 

I'll be honest, I'm not really seeing what you're seeing in that code sandbox, or at least not understanding what you're exactly describing.

But regardless of that, I suspect this might be a duplicate of https://github.com/twilio-labs/paste/issues/3097

**Comment by bthomasstill** [comment] 2023-03-29 08:59
Ah, I updated the code sandbox - it is more pronounced when the combobox is wrapped in a Flex instead of a Box. You can take a look now and confirm, but sounds like it probably is a duplicate.

**Comment by TheSisb** [comment] 2023-04-03 16:03
Fixed in https://github.com/twilio-labs/paste/pull/3142. Will be released in the next version of Paste which I will publish by EoD.

**Comment by SiTaggart** [comment] 2023-04-04 18:23
This should be fixed in `19.0.1`. Please let us know if it isn't.

**Closed by SiTaggart** 2023-04-04 18:23 UTC
