### ISSUE TITLE
Textarea's Height Changes Randomly 

### ISSUE THREAD

**Issue by SinaTaavon** [twilio-labs/paste#2034] opened 2021-11-12 12:17 UTC
Thanks for helping make Paste better! Note: For urgent requests, reach out at **#help-design-system**

**Describe the bug**

The `Textarea` has been used in a collapsible panel, when the panel is open the height of `Textarea` randomly changes to a much higher value e.g. `336px`, but by clicking on the component it restores its initial value of `76px`.

**To Reproduce**

For the collapsible panel, you can use the same framework used in Twilio Flex which is called `react-splitter-layout` `version: 4.0.0`,
on the right-hand side panel, you will need `Tabs `  from Paste. Inside one of the tabs, you will need two `box` which the bottom box will house the `Textarea` and the other two buttons.

**Expected behavior**

The `height` of the `Textarea` stays the same throughout the whole process until the user goes above 3 lines of text which are the specified rows in the `Textarea`.

**Screenshots**

![Kapture 2021-11-12 at 11 18 03](https://user-images.githubusercontent.com/32191839/141464432-9ce546c1-85f7-47a0-9a7d-9be7aad09992.gif)

Before clicking on the `Textarea`

![Screenshot 2021-11-12 at 11 29 39](https://user-images.githubusercontent.com/32191839/141465007-7a139c22-dae6-498c-8819-dc9bdc9dca17.png)

After clicking on `Textarea`

![Screenshot 2021-11-12 at 11 29 16](https://user-images.githubusercontent.com/32191839/141465062-f5bc3d08-a7ed-4e42-adf1-6cd0b87fb927.png)

Note: The `inline-style` that you can see on the `textarea` is applied by the Paste framework and is not a custom CSS.

**Desktop (please complete the following information):**
 - OS: MacOS V: 11.5.2
 - Browser Chrome
 - Version 95.0.4638.69 (Official Build) (x86_64)

**Additional context**
We have also tried to use Emotion to overside the properties, but the new properties get ignored and won't apply the new CSS style.

Thank you for your time and efforts :)

**Comment by SiTaggart** [comment] 2021-11-12 22:49
Hi @SinaTaavon 

To help speed up the process of debugging, would it be possible for you to create a reproduction in a [CodeSandbox](https://codesandbox.io/) for us?

**Comment by shleewhite** [comment] 2021-12-16 20:49
Hi @SinaTaavon, I also apologize for the late response. 

I have looked into the bug and I believe it is happening because of how `react-splitter-layout` shows and hides content. Is there a specific reason you are using this library?

The best way to solve this would be to use the Paste `disclosure-primitive` instead because it doesn't use width/height css attribute to hide content and it is accessible out of the box. I have made [a super quick example](https://codesandbox.io/s/condescending-voice-gz28b?file=/src/components/IndexPage.tsx) of how you could use it in your context.

**Comment by moretalk** [comment] 2021-12-20 16:35
@shleewhite we are using react-splitter-layout so that we can perform drag re-sizing of the containers. Any examples of doing this in paste?

**Comment by shleewhite** [comment] 2022-01-06 03:19
@moretalk I see, I don't have any examples of that. Looking into react-splitter-layout's examples, they have a toggleable panel here: https://zesik.com/react-splitter-layout/#/sidebar.

To show/hide it, instead of changing the width they have a state: https://github.com/zesik/react-splitter-layout/blob/master/example/javascripts/components/TogglableSidebarLayout.jsx.

If implemented like this, the TextArea bug should be fixed.

**Comment by TheSisb** [comment] 2022-04-08 15:59
Hello @SinaTaavon and @moretalk,

Did this manage to resolve your issue? I am going to close this for now, however please report back if the problem persists.

**Closed by TheSisb** 2022-04-08 15:59 UTC
Labels: Type: Bug
